### ISSUE TITLE
Resonance chain entries appear in the wrong order

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#1131]
**Bug**
Resonance chain entries appear in the wrong order

**Screenshot**
In the screenshot below, you can see that "tap dance" precedes "can you teach" in the chain, though it should be the other way around.    
   
![Resonance chain entries appear in the wrong order](https://user-images.githubusercontent.com/22628444/144055385-cfa09cc0-360f-4945-b311-e4cf23f4071d.png)

**To reproduce**
Daniela says:
When I tried to re-add the predicate "can you teach" to the resonance chain, the predicates ended up in the wrong order. 
I added the predicate by clicking first on the predicate "can't imagine" and then on "can you teach".

**Fix**
Sort by discourse time, using
- UnitSeq + TokenOrder, or
- Units timestamps + word timestamps

**Comment by terrydubois** [comment]
This situation is caused when doing a sort on the UnitSeq column, which causes the sort to be a single-column sort. It can be returned to discourse time sort by clicking on the sort button so that the arrow faces right.

We should make it, however, that when sorting UnitSeq we will always factor in TokenOrder so this confusion does not happen.
