### ISSUE TITLE
When deleting a chunk-entry from a chain, delete the chunk too [min]

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#1344]
Provide an easy/default way to do the following:   
When deleting chunk-entry from a track or rez chain, delete the chunk too

**Comment by terrydubois** [comment]
Present dialog box in this situation: "Delete chunk as well?"

**Comment by terrydubois** [comment]
Chunks should have a field called "lock." Any chunk spawned during import is locked by default, any chunk spawned otherwise is unlocked when spawned. When a file is opened, we set all chunks to be locked. Chunks can have their lock field toggled in the Chunk tab using a lock icon.

We can use the lock field to determine whether or not the chunk is also deleted with its entry.
Unlocked chunk: deletes chunk along with entry
Locked chunk: chunk is retained, unharmed after entry is deleted
