### ISSUE TITLE
Autosave improvements

### ISSUE THREAD

**Issue by terrydubois** [johnwdubois/rezonator#1348]
- When autosaving, the screen should show the text "Autosave..." rather than "Saving..."
- On Opening Screen, add button to "Restore autosave".
- When pressed, the button will:
- Immediately force a rename, prompt user to save in MyData folder (or last saved folder)
- Open autosave.rez (now with its new name)

**Comment by johnwdubois** [comment]
Instead of depending on the user to give us a new filename, how about this? 
"Restore autosave" button does the following: 
- creates a new copy of the current file, based on the autosave file
- automatically assigns  the name "oldName + copy"
- uses a previously stored filename for the current file (saved in the ini file, or in its own file or variable?)
- saves the new copy in "myData" folder
- opens the file for the user
Alternatively, we could just use this file renaming convention to populate the suggested filename, and let the user change it if they want.
