### ISSUE TITLE
Use UTF8 for .ini text file

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#303]
**Is your feature request related to a problem?**
Rezonator should use UTF8 for .ini text files (and for all other text files as well).
For any language other than English, UTF8 is very important (for accented characters etc.).

**Describe the solution you'd like**
1. Make sure to create the .ini text file in UTF8 format. 
2. To quote the Yoyo docs on [UTF8 for text files](https://docs.yoyogames.com/source/dadiospice/002_reference/file%20handling/files/index.html):     
"Please note that for games with localizations it is very important that accented letters can be read from external files. This means that you should create the txt file in UTF8 format first and then add it into GameMaker: Studio as an included file so that it is exported on running the game and used instead of the default ANSI format txt file that is created by the GameMaker: Studio file functions when no file is previously supplied. In this way, you can read and write to it correctly with all accents and non-roman letters being maintained."
3. In addition, Rezonator should use UTF8 for all other text files as well, when possible.

**Additional context**
Relevant to #302 .

**Comment by johnwdubois** [comment]
I updated this ticket to focus specifically on the .ini file, which is the most important case to start with.

**Comment by kittynugget** [comment]
It seems the problem here is centered around localization and being able to Interact with accented characters. This is something that the native game maker functions we're using don't allow for, and to allow users to save these special characters we would have to make Rezonator able to interpret them first.

I still believe that this is an important issue, but perhaps this is a bit bigger than initially thought.
