### ISSUE TITLE
Tags in the Nav window (general)

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#408]
**Is your feature request related to a problem?**
While Rezonator makes it easy to create links between words, it doesn't make it easy for the user to add a Tag (or Note) for other kinds of information about a word, or about a unit, etc. (i.e. to annotate the data). We should give users the option to annotate.

**Describe the solution you'd like**
1. Allow the user to add a Tag to a word or other unit (i.e. to annotate it) by typing an entry into a column (or a text box) in the Nav window.
2. As a starting point, we can add 3 new Tag columns in the details pane (right pane), to be displayed to the right of the "Text" column in the Nav window. The column headers may be labeled:
- Tag 1
- Tag 2
- Tag 3
3. It's important that this information be accessible to the user:
- in the Grid view, as attached to the Word or VizWord grids
- in the saved CSV files, as attached to the Word or VizWord grids
4. Allow the user to rename the column header, and allow this name to be displayed in GridView, and saved in the CSV files.

**Additional context**
The same approach can be used to add a Tag in the left pane of the Nav window (e.g. about a Line, Unit, Word, or Stack).
See also #213, #424 

**Checklist w/ dev hours**
- [x] Token Tags - 6 hr
- [x] Unit Tags - 6 hr

**Comment by Georgio-Klironomos** [comment]
### I think this might be the best way to do it!
"An alternative strategy for unit-level tags is to create a new pane that would sit on TOP of the right pane, rather than displacing either of the panes we have now.  Assuming the left pane is showing the unit level (as in Read mode), the user would choose between having the right pane show word-level tags for the currently selected unit (one-to-many, as we have now), OR unit-level tags (one-to-one, where each line of the new right-side pane corresponds to one line of the left pane). Because the new pane would occupy the same space as the current right pane, this might be an easier way to manage the available screen real estate with minimal disruption."

**Comment by Georgio-Klironomos** [comment]
@johnwdubois Both token and Unit level tags have been implemented, now they'll need to be user tested.

**Comment by Georgio-Klironomos** [comment]
Feature has been user tested thoroughly and the functionality is where we want it. Custom fields  and tags are saved and loaded with Rez files, and old rez files work with the tool. Possible polish found with user tests will be turned into separate tickets.
