### ISSUE TITLE
10,000 link test

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#466]
**Background**
Rezonator should be able to easily handle 10,000 rez links, without slowing down excessively.

**Describe the solution you'd like**
1. Create a test of FPS for creating, modifying, displaying, and scrolling with 10,000 rez links. (This should not be considered an unusally large number. Some users may routinely create this many links, or more.) 
2. The links should include a mix of easy links (parallel, no crosses) and hard links (crosses that could trigger a race to infinity).
3. Run it regularly, checking often to be sure that the latest version of Rezonator does not slow down excessively.
4. Once Rezonator is fast with 10,000 rez links, try 100,000, then 1,000,000.
5. Test with a large number of Track links and Stacks as well.

**Comment by Georgio-Klironomos** [comment]
@johnwdubois Because of the current structure of the Link grid, Rezonator has difficulty handling even 1000 links. It slows down significantly once it reaches this point, due to excessive searching, constant realignments, and massive amounts of drawing to render all of these links. Once we restructure the link grid to not be based on searching, this performance will improve incredibly, and we can begin testing with much larger amounts of links.
