### ISSUE TITLE
User friendly export: Advanced

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#470]
**Background**
Users may be confused by the structure and content of the files exported from Rezonator (e.g. CSV files). Unfortunately, Rezonator will have limited value for users if they cannot easily find the information they need in the exported files. Even if the information is there, it may not be obvious where it is. So all data in the exported files should be presented in a readily understandable form.      

NOTE: The detailed comments by Ryan need to be considered, and decisions made about which of these features to include or exclude.

**What to export: Strings**
Some Rezonator grids include _implicit_ pointers to words, but what these words are may not be obvious to the users. For example, the Unit grid contains a list of the WordId's for all the Tokens/Words that make up the Unit; but currently, it does not contain the strings corresponding to the Text of these words. This leaves the user in the dark.     
1. For each Unit in the Unit grid, include a string that corresponds to the concatenated Text of all the Words in the Unit. (Use the Text field, not the Transcript field, because that's too complicated.)
- Sometimes the corpus data will provide a Unit-level field containing a string representing the Text of the whole Unit. This string should be retained as an attribute of the Unit, which can be called Text.
- Alternatively, it may be necessary to create this string by concatenating the text for all the words in the Unit. This field can be called Text_Concat, to make it clear that is was created by Rezonator
- It is possible to include both Text and Text_Concat in the same grid (even though these may somewhat redundant, containing nearly identical strings)
2. For each row in an exported grid that contains one or more pointers to words (e.g. 1 or more WordId's), include a string that corresponds to the concatenated Text of all the Words in the Unit. (Use the Text field rather than the Transcript field, which is too complicated.)
3. Note that the Link grid also contains pointers to words, include a string corresponding to the Text of
- the Source word
- the Goal word  
4. If the Source or Goal is a Chunk, include a string corresponding to the concatenated Text of the words in the Chunk.
5. In general, any time we need to draw a string (including a concatenation of strings) in the Nav window, we should be sure to cache the string. 

**Documentation**
1. Make sure that users know how to easily find and understand the information they need about the data they have created within Rezonator.    
2. Put the exported CSVs in a location (folder) that is easy to find. 
3. Create documentation that helps users easily find the data they have created within Rezonator.    
4. As far as possible, make it obvious to the user how the data in the grids are relevant to them.    

**What to export: .rez file**
To make the .rez file export more friendly to users (and to Salt/Pepper #515 ), it is important to make the .rez JSON more readable, with guidance from the following:    
- [**Beautifying  JSON** (Yellow Afterlife)](https://yal.cc/gamemaker-beautifying-json/) 

**Bonus: FPS boost from caching strings**
By storing/caching in the relevant grid every string that will be needed by Rezonator for displaying to the screen, we can reduce the need to do string processing (especially string concatenation) in real time. This _may_ provide a significant FPS speed boost.

**Comment by kayaulai** [comment]
Here are my suggestions for some of the tables. I intend to add everything that's meaningful to the user, but at the same time I do think we need to retain some fields (such as primary keys) that will be necessary for analysis even if they are not inherent to the data. I can restructure the tables to contain the following information, and to drop the rest, quite easily in R - in fact I have largely done this in winter break  - but it may be more user friendly to do this in Rezonator.

I also hope to have a good balance between storing as little redundant information as possible, and storing as much information as may be useful. I plan for RezonateR to have a variety of easy-to-use functions for e.g. joining tables. So I suggest that we only add redundant information if it will make a *reader* of the tables happy (hence adding the strings), not necessarily making it easier for someone who wants to *analyse* them (which I will do in RezonateR).

These tables are made with the assumption that we will support custom annotations.

**Word**

Not much needs to be dropped.

Field|Type|Description
--|--|--|
docID|String|For when users concatenate multiple documents.
wordID|String|Primary key
unitID|String|For linking to Unit table
wordSeqBegin|Integer|When the word or chunk begins. Probably not needed in most cases, but if our research question is related to end weight, for example, this would be useful information in combination with unit lengths.
wordSeqEnd|Integer|When the word or chunk ends.
wordText|String|The word without >L2 transcriptions (SBC), or equivalent in other transcription systems. Renamed from wordToken, which is a somewhat opaque name. Concatenated for chunks.
wordTranscript|String|The word with all transcription symbols present, same as wordText if the transcription only has words and punctuation. Concatenated for chunks.
wordStart|Double|Start time of the word.
wordEnd|Double|End time of the word.
wordType|Integer|Is it a PRE? Predicate? Something else? (0 by default, only >0 if it belongs to a specific type.)
Other|Various|Word- and chunk-level annotations as defined as the user or source corpus, e.g. animacy, NP type.

*Note*: I'm not sure entirely sure if it is the best idea to continue with our practice of putting words and chunks in the same table. I can definitely see advantages in keeping a word table, and then having a separate chunks table that stores everything (words *and* chunks) that have boxes around them. Even if this is not done natively in Rezonator's internal representation, it might be more user-friendly for the reader. In this case, the Word table would just have wordSeq, The Chunk table would have chunkSeqBegin, chunkSeqEnd, etc. Annotations would be stored only in the Chunk table and not in the Word table in this case.

Again, if it is not possible to change it this way inside Rezonator at this stage, I can do it within RezonateR.

**Unit**

Field|Type|Description
--|--|--|
docID|String|For when users concatenate multiple documents.
unitID|String|Primary key
unitSeq|Integer|Instead of calling it uID as it currently is (which is confusing), I propose to call it uSeq so that it gives us the coarse timescale, in a paradigm with wordSeq which gives us the fine timescale. Its data type (integer) highlights the fact that the column is intended not as an ID, but as a number for *locating* the unit.
unitWordIDList| String array | wordIDs of the words.
unitStart|Double|Start time of the unit.
unitEnd|Double|End time of the unit.
participantName|String|Self-explanatory.
participantID|String|To link to the participant table. Multiple people with the same name is common - you'd probably find a lot of Tashis and Tenzins in a Tibetan corpus, and the SBC had a document with three men of the same name - so this is quite necessary. I prefer this name to the current pID, which is less transparent.
unitText|String|The unit text created by concatenating together the wordTexts. I call it unitText instead of just Text as Jack suggested because one can imagine a situation in which the user wants to join two tables and retain the text both for Units and the other unit.
unitTranscript|String|The unit text with all transcription symbols present, where necessary. This should be the original text.
Other|Various|Unit-level annotations as defined by the user. I think this would render Tag obsolete.

For the SBC, uniTranscript is original, unitText is created by concatenating the words without higher-level transcription symbols.

*Drop*: ParticipantColor, DiscoColor

**Link**
Field|Type|Description
--|--|--|
docID|String|For when users concatenate multiple documents.
linkID|String|Primary key
tierID|String|Tier of the link.
tierName|String|Name of the tier.
sourceType|String|Type of the source.
sourceWordID|String|wordID of the source.
sourceUnitID|String|unitID of the source.
sourceText|String|Text of the source.
sourceTime|Double|Time when the source was uttered.
goalType|String|Type of the goal.
goalUnitID|String|unitID of the goal.
goalWordID|String|wordID of the goal.
goalText|String|Text of the goal.
goalTime|Double|Time when the goal was uttered.
sourceClickTime|Double|Time when the user clicked on the source. Probably only useful for experiments.
goalClickTime|Double|Time when the user clicked the goal. Probably only useful for experiments.
Other|Various|Custom link-level annotations.


*Drop*: Focus, Dead, Tilt

**Chain tables (rez, track and future chain types)**
Field|Type|Description
--|--|--|
docID|String|For when users concatenate multiple documents.
chainID|String|Primary key
tierID|String|Tier of the chain.
linkIDList|String array|List of links IDs involved
chainName|String|Name of the chain.
chainText|String array|Text of each word/chunk involved in the chain.
Other|Various|Custom chain-level annotations.

*Dropped*: color inFilter, align, tiltSum, author (at least until we have a better author management system)

**Stack**
Field|Type|Description
--|--|--|
docID|String|For when users concatenate multiple documents.
stackID|String|Primary key
unitIDList|String array|List of unit IDs involved
stackName|String|Name of the stack.
stackText|String array|Text of each unit involved in the stack.
Other|Various|Custom stack-level annotations. I believe this renders Caption obsolete.

*Dropped*: chainID (don't think stacks are the same kinds of objects as chains, so I suggest not putting them in the same ID list), chainState, color, inFilter, align, tiltSum, author

**Participant**

This is a new table.

Field|Type|Description
--|--|--|
participantName|String|Self-explanatory.
participantID|String|To link to the participant table. Multiple people with the same name is common - you'd probably find a lot of Tashis and Tenzins in a Tibetan corpus, and the SBC had a document with three men of the same name - so this is quite necessary. I prefer this name to the current pID, which is less transparent.
docIDList|String array|List of documents where a speaker appears.
Other|Various|Participant demographic information as defined by the user.

**Tier**

This is a new table.

Field|Type|Description
--|--|--|
tierID|String|Primary key
tierName|String|Name of the tier.
sourceType|String|Type required of sources, if applicable. e.g. PREs for track chains.
endType|String|Type required of ends, if applicable. e.g. PREs for track chains.
directionality|Boolean|Whether directionality is meaningful. Not for coreference, and probably not for resonance (are you really rezonating to the previous IU or the one before that?) but meaningful for bridging.
description|String array|A description of what it is for.
linkAnnotations|String array|An array describing what kind of annotations links of that tier can bear.
chainAnnotations|String array|An array describing what kind of annotations chains of that tier can bear.

**Comment by Georgio-Klironomos** [comment]
As soon as Brady and Terry finish up the CSV import, they'll get to work on continuing this task.

**Comment by johnwdubois** [comment]
To make the .rez file export more friendly to users (and to Salt/Pepper), it is important to make the .rez JSON more readable, with guidance from the following:    
- [**Beautifying  JSON** (Yellow Afterlife)](https://yal.cc/gamemaker-beautifying-json/)
