### ISSUE TITLE
Small user interface on high resolution screens

### ISSUE THREAD

**Issue by gtroiani** [johnwdubois/rezonator#521]
**What is the background of this feature request? Please describe.**
The user interface of Rezonator on laptops with high resolution screens is extremely small, to the point it makes it difficult to install and use the program.

**Describe what to do for the development of this feature**
Could we expand the Zoom scale that is currently under the Settings to allow users to increase the size of all fonts even more?

**Additional context**
This is the view upon installing the software (before I could increase the font size). The rest of the screen is there for reference.
![install](https://user-images.githubusercontent.com/26060089/89237277-a1430480-d5a7-11ea-8c59-70906eef8c6d.png)

This is the software after I could zoom in to the maximum limit allowed. The strings of text are fine, but the rest of the interface would be more accessible if bigger.
![Rezonator_high_screen](https://user-images.githubusercontent.com/26060089/89236721-2fb68680-d5a6-11ea-89cc-491e8eed4c1f.png)

**Comment by johnwdubois** [comment]
I agree this is important. Here's some evidence:
"If a touch screen is going to be used, regardless of the approach, it appears that buttons should be at least 20mm. Using anything smaller may result in significant performance decrements. A compromise usually has to be made between button size and available screen space,or “real estate”. If this tradeoff must be made, it appears that 20mm is the most optimal size, since using larger buttons does not provide enough benefit to performance to justify using the extra space." 
[**Source: W3C Research on Touch/Pointer Target Size**](https://www.w3.org/WAI/GL/mobile-a11y-tf/wiki/Summary_of_Research_on_Touch/Pointer_Target_Size#:~:text=If%20a%20touch%20screen%20is,%2Cor%20%E2%80%9Creal%20estate%E2%80%9D.)
