### ISSUE TITLE
Crash when sorting by Utterance

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#576]
**Bug**
Rezonator crashes when sorting by "Utterance" in the Nav window Contents pane, in Stack mode.
 (Rez 0.8.86)

**To Reproduce**
1. Make some Stacks
2. In the Nav window Contents pane, sort by "Utterance"
3. See FATAL ERROR 

**What to do**
Allow sorting by "Utterance".

___________________________________________
############################################################################################
FATAL ERROR in
action number 1
of Draw Event
for object obj_panelPane:

ds_list_size argument 1 incorrect type (undefined) expecting a Number (YYGI32)
at gml_Script_scr_sortChainGrid
############################################################################################
--------------------------------------------------------------------------------------------
stack frame is
gml_Script_scr_sortChainGrid (line -1)
gml_Script_scr_panelPane_drawChainContentsLoopClipped
gml_Object_obj_panelPane_Draw_0

**Comment by kittynugget** [comment]
hey @johnwdubois  we're having trouble replicating this error. Do you have any other ideas for why this crash occurred, we've tried sorting by utterance on multiple stacks across multiple file formats and haven't encountered a crash yet. Hopefully the bug was solved, but we are currently still unsure about the root of the issue

**Comment by Georgio-Klironomos** [comment]
The bug appears to be gone, but Terry is creating safeguards to prevent it and we'll keep an eye out for it.
