### ISSUE TITLE
Quick Stacks not working in Search Screen

### ISSUE THREAD

**Issue by Georgio-Klironomos** [johnwdubois/rezonator#628]
**What is the background of this bug report?**
Single stack creation is working fine within search screen, but trying to create quick stacks does not work.

**To Reproduce**
1. Go to the Search Screen
2. Click and Drag along the speaker labels while in Track mode
3. See that only one (or sometimes none) line was put into the Stack

**Describe what to do for the desired behavior**
Quick stacks should work in the Search Screen as they do in the Main Screen.

**Desktop (please complete the following information):**
 - OS: Windows. MacOS
 - Version: 0.9.0.2

**What is the estimated development time?**
2 Hours

**Describe the individual development tasks that make up this feature (along with a dev hour estimate)**
- [ ] Debug to ensure quick stacks are functional - 1 hr
- [ ] Test throughout Main and Search screen to ensure proper functionality after bug fix- 1 hr

**Related**
#250

**Comment by johnwdubois** [comment]
Please note: This could be considered a feature, not a bug. There is a danger in giving the user too much freedom to make Stacks in the Search screen, because the lines displayed here may be very far apart in the conversation, and thus may not really have much to do with each other.
That said, this could be a nice feature to add,  as long as we give the user a warning about the distance between the lines they are trying to add to the Stack, before they complete the process.

**Comment by johnwdubois** [comment]
Related to #250
